swagger: '2.0'
basePath: /v1
info:
  version: '1.0'
  title: URL shortener API
  description: |
    URL shortener API
schemes:
  - https
consumes:
  - application/json; charset=utf-8
produces:
  - application/json; charset=utf-8
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
    description: |
      Для аутентификации вызовов мы используем [JWT](https://jwt.io). Cоответствующий ключ передается в заголовке.
      ```shell
       Authorization: Bearer {TOKENIZATION|PRIVATE_JWT}
      ```
      Посмотреть ваш API-ключ вы можете в личном кабинете. Ключи не разделяются на тестовые и боевые, ваш API ключ открывает доступ ко всем функциям платформы. Для тестовых транзакций используйте ID тестовых магазинов. Помните, что вы никому не должны передавать ваш API ключ!
security:
  - bearer: []
responses:
  NotFound:
    description: Объект не найден
  Unauthorized:
    description: Операция требует авторизации
  Forbidden:
    description: Операция недоступна
  BadRequest:
    description: Неверные данные запроса
    schema:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
parameters:
  requestID:
    name: X-Request-ID
    in: header
    description: Уникальный идентификатор запроса к системе
    required: true
    type: string
    maxLength: 32
    minLength: 1
  shortenedUrlID:
    name: shortenedUrlID
    in: path
    description: Идентификатор короткой ссылки
    required: true
    type: string
tags:
  - name: Shortener
    x-displayName: Короткие ссылки
    description: Получение и работа с короткими ссылками
paths:
  /shortened-urls:
    post:
      description: Создать новую короткую ссылку
      tags:
        - Shortener
      operationId: shortenUrl
      parameters:
        - $ref: '#/parameters/requestID'
        - name: shortenedUrlParams
          description: Параметры для создания короткой ссылки
          in: body
          required: true
          schema:
            $ref: '#/definitions/ShortenedUrlParams'
      responses:
        '201':
          description: Короткая ссылка создана
          schema:
            $ref: '#/definitions/ShortenedUrl'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
  '/shortened-urls/{shortenedUrlID}':
    get:
      description: Получить данные созданной короткой ссылки
      operationId: getShortenedUrl
      tags:
        - Shortener
      parameters:
        - $ref: '#/parameters/requestID'
        - $ref: '#/parameters/shortenedUrlID'
      responses:
        '200':
          description: Данные короткой ссылки
          schema:
            $ref: '#/definitions/ShortenedUrl'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
        '404':
          $ref: '#/responses/NotFound'
    delete:
      description: Удалить короткую ссылку
      operationId: deleteShortenedUrl
      tags:
        - Shortener
      parameters:
        - $ref: '#/parameters/requestID'
        - $ref: '#/parameters/shortenedUrlID'
      responses:
        '204':
          description: Короткая ссылка удалена
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/Forbidden'
        '404':
          $ref: '#/responses/NotFound'
definitions:
  ShortenedUrl:
    type: object
    required:
      - id
      - shortenedUrl
      - sourceUrl
      - expiresAt
    properties:
      id:
        type: string
      shortenedUrl:
        type: string
        format: uri
      sourceUrl:
        type: string
        format: uri
      expiresAt:
        type: string
        format: date-time
  ShortenedUrlParams:
    type: object
    required:
      - sourceUrl
      - expiresAt
    properties:
      sourceUrl:
        type: string
        format: uri
      expiresAt:
        type: string
        format: date-time
